"""move currency from balance transactions to user

Revision ID: 7c8c90970b4e
Revises: f8ee6b0e36f1
Create Date: 2026-08-29 12:40:20.714578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7c8c90970b4e'
down_revision: Union[str, None] = 'f8ee6b0e36f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_transactions', 'currency')
    op.add_column('users', sa.Column('currency', sa.Enum('USD', 'IQD', name='currency'), server_default='USD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    op.add_column('balance_transactions', sa.Column('currency', postgresql.ENUM('USD', 'IQD', name='currency'), server_default=sa.text("'USD'::currency"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
