"""add user token_version

Revision ID: ba748a01a8af
Revises: b71b7912e88d
Create Date: 2026-08-29 08:59:03.940112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba748a01a8af'
down_revision: Union[str, None] = 'b71b7912e88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
