"""add giveaway tables

Revision ID: fda8ee6c9fdb
Revises: 7c8c90970b4e
Create Date: 2026-08-29 13:14:32.678479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fda8ee6c9fdb'
down_revision: Union[str, None] = '7c8c90970b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giveaways',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_date')
    )
    op.create_table('giveaway_winners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('giveaway_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('giveaway_id', 'user_id', name='uq_giveaway_winner_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('giveaway_winners')
    op.drop_table('giveaways')
    # ### end Alembic commands ###
